config/routes.rb
Rails.application.routes.draw do
  resources :hoges
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  get '/auth/:provider/callback', to: 'sessions#callback'
  post 'logout', to: 'sessions#logout'

  resources :omikujis, only: %i[index create destroy]
  resources :custom_responses, only: %i[index create destroy]
  namespace :api do
    get 'omikujis/random/:user_id' => 'omikujis#random'
    get 'custom_responses/words' => 'custom_responses#words'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/discord_info.rb
module DiscordInfo
  extend ActiveSupport::Concern

  included do
    def servers(user_token)
      JSON.parse(Discordrb::API::User.servers("Bearer #{user_token}")).map { |s| DiscordServer.new(s) }
    rescue StandardError => e
      puts e.message
      []
    end
  end

  class DiscordServer
    attr_reader :id, :name, :owner, :permissions, :features, :permission_new

    def initialize(server)
      server.tap do |s|
        @id = s['id']
        @name = s['name']
        @owner = s['owner']
        @permissions = s['permissions']
        @features = s['features']
        @permissions_new = s['permissions_new']
      end
    end
  end
end

app/models/custom_response.rb
class CustomResponse < ApplicationRecord
  belongs_to :user

  validates :key, presence: true, length: {maximum: 255, message: '反応する言葉は255文字以内にしてください'}
  validates :response, presence: true, length: {maximum: 1000, message: '返信内容は1000文字以内にしてください'}
  validate :key_response_unqique

  def key_response_unqique
    cr = CustomResponse.where(key: key)
    cr = cr.filter { |r| r.response == response }
    errors.add(:response, '重複した反応が既に登録されています') if cr.present?
  end
end

app/models/day_omikuji.rb
class DayOmikuji < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}
  validates :discord_id, presence: true, uniqueness: true, length: {maximum: 50}
end

app/models/omikuji.rb
class Omikuji < ApplicationRecord
  belongs_to :user
  validates :name, presence: true, uniqueness: true, length: {maximum: 50}

  scope :random, -> { offset(rand(count)).limit(1).first }

  def self.random_by_discord_id(discord_id)
    day = DayOmikuji.find_by(discord_id: discord_id, updated_at: Time.zone.now.all_day)
    return day.name if day.present?

    omikuji_day = DayOmikuji.find_or_initialize_by(discord_id: discord_id)
    omikuji_day.name = random.name
    omikuji_day.save!

    omikuji_day.name
  end
end

app/models/user.rb
class User < ApplicationRecord
  include DiscordInfo
  has_many :omikujis

  validates :name, presence: true
  validates :discord_id, presence: true, uniqueness: true
  validates :image_url, presence: true

  def guilds
    raise 'tokenがある状態で取得して下さい' unless token

    servers(token)
  end

  def asakusa?
    guilds.map(&:id).include? Constants::ASAKUSA_ID
  end
end

app/controllers/api/custom_responses_controller.rb
class Api::CustomResponsesController < ApplicationController
  def words
    if params[:word].blank?
      render json: { words: [] }
      return
    end

    words = CustomResponse.all
                          .filter { |r| params[:word].include?(r.key) }
                          .group_by { |r| r.key }
                          .map{ |_, r| r[rand(r.length)]}
                          .map(&:response)
    render json: { words: words }
  end
end

app/controllers/api/omikujis_controller.rb
class Api::OmikujisController < ApplicationController
  def random
    omikuji = Omikuji.random_by_discord_id(params[:user_id])
    render json: {name: omikuji}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UserStatus
end

app/controllers/concerns/user_status.rb
module UserStatus
  extend ActiveSupport::Concern

  included do
    helper_method :logged_in_user

    def logged_in?
      session[:user].present? && session[:user]['id'].present?
    end

    def logged_in_user(refresh: false)
      unless logged_in?
        @logged_in_user = nil
        return nil
      end

      @logged_in_user = User.find_by(id: session[:user]['id']) if refresh

      @logged_in_user ||= User.find_by(id: session[:user]['id'])
    end

    def logged_out
      session[:user] = nil
    end

    def logged_in_with_discord(auth_hash)
      user = User.find_or_initialize_by(discord_id: auth_hash[:uid])
      user.name = auth_hash[:info][:name]
      user.image_url = auth_hash[:info][:image]
      user.token = auth_hash[:credentials][:token]
      user.expires_at = auth_hash[:credentials][:expires_at]
      user.refresh_token = auth_hash[:credentials][:refresh_token]

      return nil unless user.asakusa?

      user.save!
      session[:user] = user

      user
    end

    def refresh!
      if logged_in_user.expires_at < Time.current.to_i
        oauth = OmniAuth::Strategies::Discord.new(
          nil,
          Constants::DISCORD_CLIENT_ID,
          Constants::DISCORD_CLIENT_SECRET
        )
        token = OAuth2::AccessToken.new(
          oauth.client,
          logged_in_user.token,
          { refresh_token: logged_in_user.refresh_token }
        )
        new_token = token.refresh!
        if new_token.present?
          logged_in_user.update(
            token: new_token.token,
            expires_at: new_token.expires_at,
            refresh_token: new_token.refresh_token
          )
        else
          puts("DAMN - DIDN'T WORK!")
        end
      end

      logged_in_user(refresh: true)
    end
  end
end

app/controllers/custom_responses_controller.rb
class CustomResponsesController < ApplicationController
  before_action :set_custom_response, only: :destroy

  def index
    @custom_responses = CustomResponse.order(key: 'ASC').order(created_at: 'DESC')
  end

  def create
    unless logged_in?
      redirect_to custom_responses_path, alert: 'おみくじの削除に失敗しました'
      return
    end
    custom_response = CustomResponse.new(custom_response_params)
    custom_response.user = logged_in_user
    begin
      custom_response.save!
    rescue ActiveRecord::RecordInvalid => _e
      redirect_to custom_responses_path, alert: custom_response.errors.messages.map {|_, val| val}.join("\n")
      return
    end

    redirect_to custom_responses_path, notice: "#{custom_response.key} を作成しました！"
  end

  def destroy
    unless logged_in?
      redirect_to custom_responses_path, alert: 'おみくじの削除に失敗しました'
      return
    end
    @custom_response.destroy

    redirect_to custom_responses_path, notice: 'おみくじの削除に成功しました'
  end

  private

  def custom_response_params
    params.require(:custom_response).permit(:key, :response)
  end

  def set_custom_response
    @custom_response = CustomResponse.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/omikujis_controller.rb
class OmikujisController < ApplicationController
  before_action :set_omikuji, only: :destroy

  def index
    @omikujis = Omikuji.all
  end

  def create
    omikuji = Omikuji.new(omikuji_params)
    omikuji.user = logged_in_user
    omikuji.save!

    redirect_to omikujis_path, notice: "#{omikuji.name} を作成しました！"
  end

  def destroy
    if logged_in_user != @omikuji.user
      redirect_to omikujis_path, alert: 'おみくじの削除に失敗しました'
      return
    end

    @omikuji.destroy

    redirect_to omikujis_path, notice: 'おみくじの削除に成功しました'
  end

  private

  def omikuji_params
    params.require(:omikuji).permit(:name)
  end

  def set_omikuji
    @omikuji = Omikuji.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # If you're using a strategy that POSTs during callback, you'll need to skip the authenticity token check for the callback action only.
  skip_before_action :verify_authenticity_token, only: :callback

  def logout
    logged_out
    redirect_to omikujis_path
  end

  def callback
    logged_in_with_discord(auth_hash)
    redirect_to root_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user
    session[:user]
  end
end

app/views/custom_responses/index.html.haml
.overflow-x-auto
  .min-w-screen.min-h-full.bg-gray-100.flex.items-center.justify-center.font-sans.overflow-hidden
    .w-full{:class => "lg:w-3/4"}
      %img.mx-auto.h-60.mt-4{ src: 'https://japaclip.com/files/shrine-torii.png'}
      - if logged_in_user.present?
        = form_with scope: :custom_response, local: true, class: "my-4 flex" do |f|
          = f.text_field :key, placeholder: '反応する言葉', required: true, class: 'w-3/4 rounded-l-lg p-4 border-t mr-0 border-b border-l text-gray-800 border-gray-200 bg-white'
          = f.text_field :response, placeholder: '返信内容', required: true, class: 'w-3/4 rounded-l-lg p-4 border-t mr-0 border-b border-l text-gray-800 border-gray-200 bg-white'
          %button.px-8.rounded-r-lg.bg-yellow-400.text-gray-800.font-bold.p-4.uppercase.border-yellow-500.border-t.border-b.border-r{class: 'w-1/4'}
            自動返信を作成
      .bg-white.break-all.shadow-md.rounded.my-6
        %table.w-full.table-fixed
          %thead
            %tr.bg-gray-200.text-gray-600.uppercase.text-sm.leading-normal
              %th.py-3.px-6.text-left{class: 'w-3/12'} 反応する言葉
              %th.py-3.px-6.text-left{class: 'w-6/12'} 返信内容
              %th.py-3.px-6.text-left{class: 'w-2/12'} ユーザ
              %th.py-3.px-6.text-center{class: 'w-1/12'} 操作
          %tbody.text-gray-600.text-sm.font-light
            - @custom_responses.each do |custom_response|
              %tr.border-b.border-gray-200.hover:bg-gray-100
                %td.py-3.px-6.text-left
                  .flex.items-center
                    %span.font-medium
                      = custom_response.key
                %td.py-3.px-6.text-left
                  .flex.items-center
                    %span.font-medium
                      = custom_response.response
                %td.py-3.px-6.text-left
                  .flex.items-center
                    .mr-2
                      %img.w-6.h-6.rounded-full{src: custom_response.user.image_url}/
                    %span
                      = custom_response.user.name
                %td.py-3.px-6.text-center
                  .flex.item-center.justify-center
                    - if logged_in_user.present?
                      .w-4.mr-2.transform.hover:text-purple-500.hover:scale-110
                        = link_to custom_response, method: :delete, data: { confirm: "#{custom_response.key} を削除しますか？" } do
                          %svg{:fill => "none", :stroke => "currentColor", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
                            %path{:d => "M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}

app/views/home/index.html.haml
home less

app/views/layouts/_flash.html.haml
- if notice.present?
  .text-white.px-6.py-4.border-0.rounded.relative.my-4.bg-teal-500.bg-opacity-50
    %span.text-xl.inline-block.mr-5.align-middle
      %i.material-icons
        done_outline
    %span.inline-block.align-middle.mr-8.font-bold= notice
    %button.absolute.bg-transparent.text-2xl.font-semibold.leading-none.right-0.top-0.mt-4.mr-6.outline-none.focus:outline-none
- if alert.present?
  .text-white.px-6.py-4.border-0.rounded.relative.my-4.bg-red-500.bg-opacity-50
    %span.text-xl.inline-block.mr-5.align-middle
      %i.material-icons
        done_outline
    %span.inline-block.align-middle.mr-8.font-bold= alert
    %button.absolute.bg-transparent.text-2xl.font-semibold.leading-none.right-0.top-0.mt-4.mr-6.outline-none.focus:outline-none

app/views/layouts/_header.html.haml
%nav.flex.items-center.justify-between.flex-wrap.bg-teal-500.p-6
  .flex.items-center.flex-shrink-0.text-white.mr-6
    %img{class: "inline-block mx-auto sm:mx-0 sm:flex-shrink-0 h-16 sm:h-12 rounded-full", src: 'https://cdn.discordapp.com/icons/281756793506627584/03605369fd0399899e3321bd3e21019f.png?size=128'}
    %span.font-semibold.text-xl.tracking-tight あさくさ
  .block.lg:hidden
    %button.flex.items-center.px-3.py-2.border.rounded.text-teal-200.border-teal-400.hover:text-white.hover:border-white
      %svg.fill-current.h-3.w-3{:viewbox => "0 0 20 20", :xmlns => "http://www.w3.org/2000/svg"}
        %title Menu
        %path{:d => "M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"}
  .w-full.block.flex-grow.lg:flex.lg:items-center.lg:w-auto
    .text-sm.lg:flex-grow
      %a.block.mt-4.lg:inline-block.lg:mt-0.text-teal-200.hover:text-white.mr-4{:href => omikujis_path}
        神社
      %a.block.mt-4.lg:inline-block.lg:mt-0.text-teal-200.hover:text-white.mr-4{:href => custom_responses_path}
        bot返信
    %div
      - if logged_in_user.present?
        .inline-block.text-sm.px-4.py-2.leading-none.border.rounded.text-white.border-white.hover:border-transparent.hover:text-teal-500.hover:bg-white.mt-4.lg:mt-0
          = link_to 'Log Out', logout_path, method: :post
        %div.block.mt-4.lg:inline-block.lg:mt-0.text-teal-200.hover:text-white
          = logged_in_user.name
        %img{class: "inline-block mx-auto sm:mx-0 sm:flex-shrink-0 h-16 sm:h-10 rounded-full", src: logged_in_user.image_url}
      - else
        .inline-block.text-sm.px-4.py-2.leading-none.border.rounded.text-white.border-white.hover:border-transparent.hover:text-teal-500.hover:bg-white.mt-4.lg:mt-0
          = link_to 'Discord Login', "/auth/discord", method: :post

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiscordOmikuji</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-gray-100">
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>

app/views/omikujis/index.html.haml
.overflow-x-auto
  .min-w-screen.min-h-full.bg-gray-100.flex.items-center.justify-center.font-sans.overflow-hidden
    .w-full{:class => "lg:w-3/4"}
      %img.mx-auto.h-60.mt-4{ src: 'https://japaclip.com/files/shrine-torii.png'}
      - if logged_in_user.present?
        = form_with scope: :omikuji, local: true, class: "my-4 flex" do |f|
          = f.text_field :name, placeholder: '大吉', required: true, class: 'w-3/4 rounded-l-lg p-4 border-t mr-0 border-b border-l text-gray-800 border-gray-200 bg-white'
          %button.px-8.rounded-r-lg.bg-yellow-400.text-gray-800.font-bold.p-4.uppercase.border-yellow-500.border-t.border-b.border-r{class: 'w-1/4'}
            おみくじを作成
      .bg-white.break-all.shadow-md.rounded.my-6
        %table.w-full.table-fixed
          %thead
            %tr.bg-gray-200.text-gray-600.uppercase.text-sm.leading-normal
              %th.py-3.px-6.text-left{class: 'w-9/12'} おみくじ
              %th.py-3.px-6.text-left{class: 'w-2/12'} ユーザ
              %th.py-3.px-6.text-center{class: 'w-1/12'} 操作
          %tbody.text-gray-600.text-sm.font-light
            - @omikujis.each do |omikuji|
              %tr.border-b.border-gray-200.hover:bg-gray-100
                %td.py-3.px-6.text-left.whitespace-nowrap
                  .flex.items-center
                    %span.font-medium
                      = omikuji.name
                %td.py-3.px-6.text-left
                  .flex.items-center
                    .mr-2
                      %img.w-6.h-6.rounded-full{src: omikuji.user.image_url}/
                    %span
                      = omikuji.user.name
                %td.py-3.px-6.text-center
                  .flex.item-center.justify-center
                    -# .w-4.mr-2.transform.hover:text-purple-500.hover:scale-110
                    -#   %svg{:fill => "none", :stroke => "currentColor", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
                    -#     %path{:d => "M15 12a3 3 0 11-6 0 3 3 0 016 0z", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
                    -#     %path{:d => "M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
                    -# .w-4.mr-2.transform.hover:text-purple-500.hover:scale-110
                    -#   %svg{:fill => "none", :stroke => "currentColor", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
                    -#     %path{:d => "M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}
                    - if logged_in_user.present? && logged_in_user == omikuji.user
                      .w-4.mr-2.transform.hover:text-purple-500.hover:scale-110
                        = link_to omikuji, method: :delete, data: { confirm: "#{omikuji.name} を削除しますか？" } do
                          %svg{:fill => "none", :stroke => "currentColor", :viewbox => "0 0 24 24", :xmlns => "http://www.w3.org/2000/svg"}
                            %path{:d => "M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16", "stroke-linecap" => "round", "stroke-linejoin" => "round", "stroke-width" => "2"}